### ISSUE TITLE
Wrong compiled colors

### ISSUE THREAD

**Issue by fknop** [Arthie/tailwindcssinjs#2]
Hey!

I just tried your library because it supports the latest versions of tailwind out of the box.
However, I've had some issue with colors being wrongly generated.

I have the following styled component:

```typescript 
const SelectableRowContainer = styled.div<SelectableRowProps>`
  ${props => (props.selected ? tw`border-yellow-500` : tw`border-gray-300`)};
  ${tw`border-solid border-2 w-full cursor-pointer flex`};
`
```

When compiling it with Babel, it generates the following:

```javascript
var SelectableRowContainer = _styledComponents["default"].div.withConfig({
  displayName: "SelectableRow__SelectableRowContainer",
  componentId: "sc-1rdb9br-0"
})(["", ";", ";"], function (props) {
  return props.selected ? {
    "--border-opacity": "1",
    "borderColor": ["#ecc94b", "rgba(236, 201, 75, var(--border-opacity))"]
  } : {
    "--border-opacity": "1",
    "borderColor": ["#e2e8f0", "rgba(226, 232, 240, var(--border-opacity))"]
  };
}, {
  "borderStyle": "solid",
  "borderWidth": "2px",
  "width": "100%",
  "cursor": "pointer",
  "display": "flex"
});
```

The --border-opacity variable  shouldn't be there. This generates the css: `border-color: #e2e8f0", "rgba(226, 232, 240, var(--border-opacity))` which is invalid. I had the same issue with a background-color.

I'm using `@tailwindcssinjs/macro` 0.3.1 and `tailwindcss` 1.4.4

**Comment by fknop** [comment]
I just tried to disable the `borderOpacity` corePlugin and it seems to generate the styles properly if that's any help!

**Comment by Arthie** [comment]
Yes, you are correct tailwind v1.4.0 added opacity utilities that changed the tailwind colors.

Pre v1.4.0
```css
.border-white {
  border-color: #fff;
}
```
After v1.4.0
```css
.border-white {
  --border-opacity: 1;
  border-color: #fff;
  border-color: rgba(255, 255, 255, var(--border-opacity));
}
```

As you noticed tailwind has now 2 `border-color` rules the first rule is there as a fallback when the browser doesn't support the CSS variable in the second rule.

Interestingly Styled-components doesn't support this syntax
`"borderColor": ["#fff", "rgba(255, 255, 255, var(--border-opacity))"]`
But it works fine in Emotion because its supports [fallbacks](https://emotion.sh/docs/object-styles#fallbacks).

Here is a sandbox I used to test this.
https://codesandbox.io/s/test-2-0piru?file=/pages/index.tsx

Not yet sure what the best solution to fix this would be since this is specific to styled-components.

**Comment by fknop** [comment]
Thanks for the information ! I'll open an issue on the styled components repository then! 

I'm closing this issue as this is not an issue related to tailwind.

**Comment by Arthie** [comment]
@tailwindcssinjs/macro now has support for custom output syntax.
This makes it possible to use @tailwindcssinjs/macro with styled-components or any other CSS-in-JS library with different syntax.
Check out the [tailwindcssinjs plugin documentation](https://github.com/Arthie/tailwindcssinjs/tree/master/packages/macro#tailwindcssinjs-plugins-experimental)

**Comment by fknop** [comment]
Thanks! I appreciate that!
